# Generated by Django 4.0 on 2021-12-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_hourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=150, null=True)),
                ('times', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'opening',
            },
        ),
    ]
