# Generated by Django 4.0 on 2021-12-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0002_opening_hourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_service_1', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_service_2', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_service_3', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_service_4', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctor_service',
            },
        ),
        migrations.CreateModel(
            name='Service_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('service_1', models.CharField(blank=True, max_length=150, null=True)),
                ('service_2', models.CharField(blank=True, max_length=150, null=True)),
                ('service_3', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_3',
        ),
    ]
