# Generated by Django 4.0 on 2021-12-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0003_doctor_service_service_pricing_remove_service_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_service',
            old_name='doctor_service_1',
            new_name='doctor_service',
        ),
        migrations.RemoveField(
            model_name='doctor_service',
            name='doctor_service_2',
        ),
        migrations.RemoveField(
            model_name='doctor_service',
            name='doctor_service_3',
        ),
        migrations.RemoveField(
            model_name='doctor_service',
            name='doctor_service_4',
        ),
    ]
