# Generated by Django 4.0 on 2021-12-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0004_rename_doctor_service_1_doctor_service_doctor_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficce_contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='oficce_contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='oficce_contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='oficce_contact',
            name='descriptions',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='oficce_contact',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
